/**
 * 內建 Workflow 範本。
 * metadata + 簡化 workflow 定義，由 template-builder 轉為完整 React Flow 格式。
 */
import { buildTemplate, type TemplateDef, type TemplateWorkflow } from './template-builder'

export interface TemplateInfo {
  id: string;
  name: string;
  icon: string;
  category: string;
  shortDescription: string;
  tags: string[];
  sampleMessages: string[];
  def: TemplateDef;
}

// ─── Helpers ───
const agent = (name: string, data?: Record<string, unknown>) => ({ type: 'agent' as const, name, data })
const auto = (name: string, data?: Record<string, unknown>) => ({ type: 'autonomous' as const, name, data })
const rag = (name: string, data?: Record<string, unknown>) => ({ type: 'rag' as const, name, data })
const code = (name: string, data?: Record<string, unknown>) => ({ type: 'code' as const, name, data })
const cond = (name: string, data?: Record<string, unknown>) => ({ type: 'condition' as const, name, data })
const loop = (name: string, data?: Record<string, unknown>) => ({ type: 'loop' as const, name, data })
const router = (name: string, data?: Record<string, unknown>) => ({ type: 'router' as const, name, data })
const human = (name: string, data?: Record<string, unknown>) => ({ type: 'human' as const, name, data })
const iter = (name: string, data?: Record<string, unknown>) => ({ type: 'iteration' as const, name, data })
const parallel = (name: string, data?: Record<string, unknown>) => ({ type: 'parallel' as const, name, data })
const http = (name: string, data?: Record<string, unknown>) => ({ type: 'http-request' as const, name, data })
const c = (from: number, to: number, fromOutput?: string) => ({ from, to, fromOutput })

export const BUILTIN_TEMPLATES: TemplateInfo[] = [
  // ─── Basic ───
  { id: 'sequential', name: 'Research & Write', icon: 'ArrowRight', category: 'Basic', shortDescription: 'Three agents collaborate: research, draft, edit.', tags: ['sequential', 'content', 'writing'], sampleMessages: ['Write a blog post about AI agent frameworks in 2026'], def: { nodes: [agent('Researcher', { instructions: 'Research the given topic thoroughly.' }), agent('Drafter', { instructions: 'Write an article based on the research.' }), agent('Editor', { instructions: 'Polish and edit the draft.' })], connections: [c(0,1), c(1,2)] } },
  { id: 'loop', name: 'Writer-Reviewer Loop', icon: 'RefreshCw', category: 'Basic', shortDescription: 'Write, review, iterate until approved.', tags: ['loop', 'review', 'quality'], sampleMessages: ['Draft a product announcement'], def: { nodes: [agent('Writer', { instructions: 'Write content on the given topic.' }), loop('ReviewLoop', { conditionType: 'contains', conditionExpression: 'APPROVED', maxIterations: 3 }), agent('Reviewer', { instructions: 'Review the draft. Reply APPROVED if good.' }), agent('Publisher', { instructions: 'Format and publish the approved content.' })], connections: [c(0,1), c(1,2,'output_1'), c(2,0), c(1,3,'output_2')] } },
  { id: 'router', name: 'Customer Service Router', icon: 'Route', category: 'Basic', shortDescription: 'Route customer queries to specialists.', tags: ['router', 'customer-service'], sampleMessages: ['I was charged twice for my subscription'], def: { nodes: [agent('Triage', { instructions: 'Classify the query into: billing, technical, or general.' }), router('Router', { routes: 'billing,technical,general' }), agent('Billing', { instructions: 'Handle billing inquiries.' }), agent('Technical', { instructions: 'Handle technical support.' }), agent('General', { instructions: 'Handle general inquiries.' })], connections: [c(0,1), c(1,2,'output_1'), c(1,3,'output_2'), c(1,4,'output_3')] } },
  { id: 'code-transform', name: 'Code Transform Pipeline', icon: 'Code', category: 'Basic', shortDescription: 'Agent output processed by Code node.', tags: ['code', 'transform'], sampleMessages: ['Analyze the pros and cons of remote work'], def: { nodes: [agent('Analyzer', { instructions: 'Analyze the topic and output findings.' }), code('Format', { transformType: 'template', template: '## Report\n\n{{input}}' }), agent('Reporter', { instructions: 'Write a polished report.' })], connections: [c(0,1), c(1,2)] } },
  { id: 'http-webhook', name: 'HTTP API Pipeline', icon: 'Globe2', category: 'Basic', shortDescription: 'Agent + HTTP call + Agent.', tags: ['http', 'api'], sampleMessages: ['查詢台北市今天的天氣'], def: { nodes: [agent('Preparer', { instructions: 'Extract parameters for the API call.' }), http('APICall'), agent('Reporter', { instructions: 'Format the API response.' })], connections: [c(0,1), c(1,2)] } },
  { id: 'parallel-experts', name: 'Parallel Multi-Expert', icon: 'Columns3', category: 'Basic', shortDescription: 'Multiple experts in parallel, then synthesize.', tags: ['parallel', 'fan-out'], sampleMessages: ['評估設立 AI SaaS 子公司的可行性'], def: { nodes: [agent('Intake', { instructions: 'Summarize the question.' }), parallel('MultiExpert', { branches: 'Legal,Technical,Financial' }), agent('Legal', { instructions: 'Legal analysis.' }), agent('Technical', { instructions: 'Technical analysis.' }), agent('Financial', { instructions: 'Financial analysis.' }), agent('Synthesizer', { instructions: 'Merge all analyses.' })], connections: [c(0,1), c(1,2,'output_1'), c(1,3,'output_2'), c(1,4,'output_3'), c(2,5), c(3,5), c(4,5)] } },
  { id: 'iteration-batch', name: 'Iteration Batch', icon: 'Repeat', category: 'Basic', shortDescription: 'Split and process each item individually.', tags: ['iteration', 'batch'], sampleMessages: ['分析：React, Vue, Angular, Svelte'], def: { nodes: [agent('Splitter', { instructions: 'Convert input into a JSON array.' }), iter('ForEach'), agent('ItemProcessor', { instructions: 'Analyze this item.' }), agent('Summarizer', { instructions: 'Compile all results.' })], connections: [c(0,1), c(1,2,'output_1'), c(1,3,'output_2')] } },
  { id: 'structured-output', name: 'Structured Output', icon: 'FileJson', category: 'Basic', shortDescription: 'JSON schema output + report.', tags: ['json', 'schema'], sampleMessages: ['分析半導體產業的競爭優勢'], def: { nodes: [agent('Analyzer', { instructions: 'Output JSON: title, summary, keyFindings, recommendation.', outputFormat: 'json_schema' }), agent('Reporter', { instructions: 'Convert JSON to readable report.' })], connections: [c(0,1)] } },
  { id: 'translator', name: 'Parallel Translator', icon: 'Languages', category: 'Basic', shortDescription: 'Translate into 3 languages simultaneously.', tags: ['translate', 'parallel'], sampleMessages: ['人工智慧正在改變我們的工作方式'], def: { nodes: [agent('Detector', { instructions: 'Detect language and pass text through.' }), parallel('Translate', { branches: 'English,Japanese,Korean' }), agent('English', { instructions: 'Translate to English.' }), agent('Japanese', { instructions: 'Translate to Japanese.' }), agent('Korean', { instructions: 'Translate to Korean.' })], connections: [c(0,1), c(1,2,'output_1'), c(1,3,'output_2'), c(1,4,'output_3')] } },
  { id: 'plan-execute', name: 'Plan and Execute', icon: 'ListChecks', category: 'Basic', shortDescription: 'Break goal into steps, execute each.', tags: ['plan', 'execute'], sampleMessages: ['規劃：評估在日本設立分公司'], def: { nodes: [agent('Planner', { instructions: 'Break goal into 3-6 steps as JSON array.' }), iter('StepLoop'), agent('Executor', { instructions: 'Execute this step.', tools: ['web_search'] }), agent('Compiler', { instructions: 'Merge all results.' })], connections: [c(0,1), c(1,2,'output_1'), c(1,3,'output_2')] } },
  // ─── Tools & Search ───
  { id: 'single-tools', name: 'Single Agent + Tools', icon: 'Bot', category: 'Tools & Search', shortDescription: 'One agent with web search.', tags: ['single', 'tools', 'search'], sampleMessages: ['What are the latest developments in .NET 10?'], def: { nodes: [agent('Assistant', { instructions: 'Helpful assistant with web search.', tools: ['web_search'] })], connections: [] } },
  { id: 'csv-log-analyzer', name: 'CSV Log Analyzer', icon: 'BarChart3', category: 'Tools & Search', shortDescription: 'Analyze CSV logs and email report.', tags: ['csv', 'log'], sampleMessages: ['分析 CSV 並寄報告'], def: { nodes: [agent('LogReader', { instructions: 'Read CSV files.', tools: ['csv_log_analyzer', 'zip_extractor'] }), agent('LogAnalyst', { instructions: 'Analyze and email report.', tools: ['send_email'] })], connections: [c(0,1)] } },
  { id: 'deep-research', name: 'Deep Research', icon: 'Search', category: 'Tools & Search', shortDescription: 'Multi-query research with synthesis.', tags: ['research', 'deep'], sampleMessages: ['深入研究生成式 AI 應用趨勢'], def: { nodes: [agent('QueryPlanner', { instructions: 'Create 3-5 search queries as JSON array.' }), iter('SearchLoop'), agent('Researcher', { instructions: 'Search and summarize.', tools: ['web_search'] }), agent('Synthesizer', { instructions: 'Compile research report.' })], connections: [c(0,1), c(1,2,'output_1'), c(1,3,'output_2')] } },
  { id: 'finance-intel', name: 'Finance Intelligence', icon: 'TrendingUp', category: 'Tools & Search', shortDescription: 'Financial news scanner.', tags: ['finance', 'news'], sampleMessages: ['台積電 CoWoS 產能分析'], def: { nodes: [agent('NewsScanner', { instructions: 'Generate search queries and scan news.', tools: ['serper_search'] }), agent('Screener', { instructions: 'Filter top article URLs.' }), agent('ContentExtractor', { instructions: 'Extract article text.', tools: ['tavily_extract'] }), agent('Analyst', { instructions: 'Write financial intelligence report.' })], connections: [c(0,1), c(1,2), c(2,3)] } },
  { id: 'lead-outreach', name: 'Lead Outreach', icon: 'Mail', category: 'Tools & Search', shortDescription: 'Research, draft, approve, send email.', tags: ['lead', 'email'], sampleMessages: ['研究 Gogoro 並寫合作提案信'], def: { nodes: [agent('LeadResearcher', { instructions: 'Research the company.', tools: ['web_search'] }), agent('EmailDrafter', { instructions: 'Draft outreach email.' }), human('ReviewDraft', { inputType: 'approval', prompt: 'Approve to send, reject to re-draft.' }), agent('EmailSender', { instructions: 'Send email.', tools: ['send_email'] })], connections: [c(0,1), c(1,2), c(2,3,'output_1')] } },
  // ─── RAG & Files ───
  { id: 'rag-pdf', name: 'PDF Q&A with RAG', icon: 'Database', category: 'RAG & Files', shortDescription: 'Upload PDF, ask questions with vector search.', tags: ['rag', 'pdf'], sampleMessages: ['Summarize the key findings'], def: { nodes: [rag('RAG'), agent('DocExpert', { instructions: 'Answer questions based on document context.' })], connections: [c(0,1)] } },
  { id: 'vision', name: 'Image Analysis', icon: 'Eye', category: 'RAG & Files', shortDescription: 'Upload image for analysis.', tags: ['vision', 'image'], sampleMessages: ['Describe what you see'], def: { nodes: [agent('VisionAgent', { instructions: 'Analyze the uploaded image.' })], connections: [] } },
  // ─── Advanced ───
  { id: 'handoff', name: 'Multi-Agent Handoff', icon: 'Users', category: 'Advanced', shortDescription: 'Coordinator delegates to specialists.', tags: ['handoff', 'delegation'], sampleMessages: ['Write a Fibonacci function in Python'], def: { nodes: [agent('Coordinator', { instructions: 'Delegate to the appropriate specialist.' }), agent('Coder', { instructions: 'Write code.' }), agent('Researcher', { instructions: 'Research topics.' })], connections: [c(0,1), c(0,2)] } },
  { id: 'mcp-agent', name: 'MCP Tool Integration', icon: 'Plug', category: 'Advanced', shortDescription: 'Agent connected to MCP server.', tags: ['mcp', 'external-tools'], sampleMessages: ['Use the echo tool'], def: { nodes: [agent('MCPAgent', { instructions: 'Use available MCP tools.' })], connections: [] } },
  // ─── Human-in-the-Loop ───
  { id: 'human-approval', name: 'Human Approval Gate', icon: 'UserCheck', category: 'Human-in-the-Loop', shortDescription: 'Draft, approve or reject.', tags: ['human', 'approval'], sampleMessages: ['Draft a product announcement'], def: { nodes: [agent('Drafter', { instructions: 'Draft content.' }), human('Review', { inputType: 'approval', prompt: 'Approve to publish, reject to revise.' }), agent('Publisher', { instructions: 'Publish approved content.' }), agent('Reviser', { instructions: 'Revise based on feedback.' })], connections: [c(0,1), c(1,2,'output_1'), c(1,3,'output_2')] } },
  { id: 'human-choice', name: 'Human Choice Branch', icon: 'GitBranch', category: 'Human-in-the-Loop', shortDescription: 'User chooses output format.', tags: ['human', 'choice'], sampleMessages: ['分析 AI 產業趨勢'], def: { nodes: [agent('Analyzer', { instructions: 'Analyze the topic.' }), human('UserChoice', { inputType: 'choice', choices: '詳細報告,簡短摘要' }), cond('CheckChoice', { conditionType: 'contains', conditionExpression: '詳細' }), agent('DetailReport', { instructions: 'Write detailed report.' }), agent('Summary', { instructions: 'Write brief summary.' })], connections: [c(0,1), c(1,2), c(2,3,'output_1'), c(2,4,'output_2')] } },
  // ─── Skills ───
  { id: 'skill-code-review', name: 'Code Review', icon: 'Target', category: 'Skills', shortDescription: 'Code review with documentation skills.', tags: ['skill', 'code-review'], sampleMessages: ['Review this code for security issues'], def: { nodes: [agent('CodeAnalyzer', { instructions: 'Analyze code for bugs and security.', skills: ['code_review'] }), agent('ReportWriter', { instructions: 'Write review report.', skills: ['technical_documentation'] })], connections: [c(0,1)] } },
  { id: 'skill-contract-review', name: 'Contract Review', icon: 'Scale', category: 'Skills', shortDescription: 'Legal review + human approval.', tags: ['skill', 'legal'], sampleMessages: ['請審查合約條款'], def: { nodes: [agent('ContractReviewer', { instructions: 'Review contract for risks.', skills: ['legal_review'] }), human('Approval', { inputType: 'approval' }), cond('Check', { conditionType: 'contains', conditionExpression: 'approve' }), agent('FinalReport', { instructions: 'Final report.' }), agent('NegotiationDraft', { instructions: 'Negotiation points.' })], connections: [c(0,1), c(1,2), c(2,3,'output_1'), c(2,4,'output_2')] } },
  { id: 'skill-research-report', name: 'SWOT Report', icon: 'BarChart3', category: 'Skills', shortDescription: 'Parallel SWOT analysis.', tags: ['skill', 'swot'], sampleMessages: ['分析半導體產業定位'], def: { nodes: [agent('Researcher', { instructions: 'Research topic.', tools: ['web_search'] }), parallel('SWOT', { branches: 'Strength,Risk' }), agent('StrengthAnalyst', { instructions: 'Strengths & opportunities.' }), agent('RiskAnalyst', { instructions: 'Weaknesses & threats.' }), agent('ReportWriter', { instructions: 'Compile SWOT report.', skills: ['formal_writing'] })], connections: [c(0,1), c(1,2,'output_1'), c(1,3,'output_2'), c(2,4), c(3,4)] } },
  // ─── Autonomous ───
  { id: 'autonomous-research', name: 'Autonomous Research', icon: 'Brain', category: 'Autonomous', shortDescription: 'AI autonomously researches and reports.', tags: ['autonomous', 'react'], sampleMessages: ['Compare GPT-4o vs Claude Opus 4'], def: { nodes: [auto('Researcher', { instructions: 'Research thoroughly. Search, verify, compile report.', tools: ['web_search', 'url_fetch'] })], connections: [] } },
  { id: 'autonomous-pipeline', name: 'Plan → Research → Report', icon: 'Brain', category: 'Autonomous', shortDescription: 'Plan + Autonomous research + Report.', tags: ['autonomous', 'pipeline'], sampleMessages: ['分析 Claude 4 技術突破'], def: { nodes: [agent('Planner', { instructions: 'Break into research questions.' }), auto('Researcher', { instructions: 'Research using web search.', tools: ['web_search', 'url_fetch'] }), agent('Reporter', { instructions: 'Write comprehensive report.' })], connections: [c(0,1), c(1,2)] } },
]

export const TEMPLATE_CATEGORIES = [...new Set(BUILTIN_TEMPLATES.map((t) => t.category))]

/** 將範本轉為完整的 React Flow nodes + edges */
export function getTemplateWorkflow(templateId: string): TemplateWorkflow | null {
  const tpl = BUILTIN_TEMPLATES.find((t) => t.id === templateId)
  if (!tpl) return null
  return buildTemplate(tpl.def)
}
